class TaskError(Exception):
	"""Raised when an issue arises with the Task class."""
